### ISSUE TITLE
Add some references to the broader project

### ISSUE THREAD

**Issue by NemoAndrea** [shantnavagarwal/Acraea_Controller#1]
I wasn't able to find any direct references to the broader LibreWater project in the main README contents[^1]. Maybe you can add a link to the project? Unless you are intimately familiar with the project, the term `Acraea` is probably unknown.

You could even consider adding https://codeberg.org/LibreWater/Acraea-Prototype (assuming that is the relevant repository) as a submodule of your git repo. The advantage of that over a link is that you then refer to a specific _version_ (i.e. commit) of the Acraea-prototype repository, which may or may not be useful.

Nice work so far!

[^1]: It is present in the homework markdown doc, but I think it would be great for people that are interested or stumble upon the project to immediately be able to see the bigger picture

**Comment by shantnavagarwal** [comment]
Thanks for the tip! I will add the the link to the main project right now. When a version of Acraea that incorporates this development is released, I will include it as a submodule as well.
